### ISSUE TITLE
this project still alive?

### ISSUE THREAD

**Issue by Altaiar** [ghaststeam/MagicEMX#33]
someone work on it?

**Comment by CrisisCorE** [comment]
If I had a PS4, I would :p

Not much is going on here. Don't expect anything usable while there isn't even a PS4 jailbreak.

**Comment by Altaiar** [comment]
Ps4 jailbreak idon`t test it 
http://jailbroken.co/index.php/ps4-jailbreak/

**Comment by CrisisCorE** [comment]
It's fake. There currently is no Jailbreak for any PS4, and there probably aren't a lot of people working on one. Also security on PS4 is much tighter than it used to be on PS3.

**Comment by Altaiar** [comment]
you right i just found this http://consolefa.ir/ps4-jailbreak-tutorial.html but you must translate it 
but it is very dangerous and it is just for play games

**Comment by ghaststeam** [comment]
Project is not dead; it's just getting a major re-design soon since the goals have changed.

**Comment by Altaiar** [comment]
this is very hopeful tank you

**Comment by ghaststeam** [comment]
@Altaiar The name's been changed since now it's going to be a multi-system in one emulator.

Some other notable changes:

1.Preliminary iOS app support I've been researching (package and binary parsing, simulation, and some HLE library mimicking code and re-factoring to attempt to run recompiled iOS (ARM->x86) apps in an isolated virtual process with GL ES 2.0/3.0 & probably tailored dynamic recompilation work too).

2.Shared JIT execution and paravirtualizing (between PS4 and Xbox One) with similar pipeline emulation exection so both of these systems and their software can be handled very similarly.

3.PS4 high-level BIOS simulation calls instead of low-level (this is known and easy to do with hacks).

Obviously much more research will be needed, but the above is the gist of what MagicEMX should be expecting to slowly become over the next few years as it becomes more stable.

**Comment by x8BitRain** [comment]
Stop pushing this shit, it's fake and always was fake, you keep your source code in a folder called TESTCCP, REAL PROFESSIONAL WOW.  Find a better way to make money than scam it out of people with your homework project.

Your own "proof of concept" useless build that doesn't do anything even knows its fake.
http://i.imgur.com/fmkt25o.png

You've already been labeled as a scam by several emulation communities, the moment you reuploaded this PS4EMX psuedocode people made posts about it being fake.

Also why the fuck would you use HLE "binary mimicking" (if that's even real) when you could just as easily use parts of QEMU to emulate iOS with LLE, you don't even know what you're talking about do you, APRIL?

**Comment by ghaststeam** [comment]
@x8BitRain 

If you're going to come here to do nothing but shout "fake," I'll just report you to GitHub.
